'use client';
import {useEffect,useMemo,useState} from 'react';
import {Search,LogOut,Clock3,ShieldCheck,Plus,FileEdit,Inbox,LoaderCircle,CheckCircle2,Hourglass,IdCard,Landmark,Vote,Car,ExternalLink,ChevronRight,LayoutDashboard,Users,IndianRupee,Activity} from 'lucide-react';

const services=[
 {id:'aadhaar',name:'Aadhaar',icon:IdCard,sub:['Aadhaar Update','Address Update','Mobile Update','Name Correction','DOB Correction','Download Aadhaar'],urls:['https://myaadhaar.uidai.gov.in/','https://myaadhaar.uidai.gov.in/','https://myaadhaar.uidai.gov.in/','https://myaadhaar.uidai.gov.in/','https://myaadhaar.uidai.gov.in/','https://myaadhaar.uidai.gov.in/'],fee:50,image:'/services/aadhaar.svg'},
 {id:'pan',name:'PAN Card',icon:Landmark,sub:['New PAN Application','PAN Correction','PAN Download'],urls:['https://www.pan.utiitsl.com/','https://www.pan.utiitsl.com/','https://www.incometax.gov.in/'],fee:100,image:'/services/pan.svg'},
 {id:'voter',name:'Voter Card',icon:Vote,sub:['New Voter Registration','Voter Correction','Download e-EPIC'],urls:['https://voters.eci.gov.in/','https://voters.eci.gov.in/','https://voters.eci.gov.in/'],fee:50,image:'/services/voter.svg'},
 {id:'dl',name:'Driving Licence',icon:Car,sub:['Learner Licence','DL Renewal','DL Services'],urls:['https://sarathi.parivahan.gov.in/','https://sarathi.parivahan.gov.in/','https://sarathi.parivahan.gov.in/'],fee:150,image:'/services/driving-licence.svg'}
];
const defaultUsers=[{username:'MASTER',name:'JOSHI JOY',role:'Master',mobile:'8074385845',email:'kandulayehoshuva84@gmail.com'},{username:'ADMIN',name:'Admin',role:'Admin',mobile:'',email:''},{username:'EMPLOYEE',name:'Employee',role:'Employee',mobile:'',email:''}];
function seedUsers(){try{return JSON.parse(localStorage.getItem('mi_users')||'null')||defaultUsers}catch{return defaultUsers}}
function seedApps(){try{return JSON.parse(localStorage.getItem('mi_apps')||'[]')}catch{return []}}
export default function Home(){
 const [user,setUser]=useState(null); const [allUsers,setAllUsers]=useState([]); const [login,setLogin]=useState(''); const [pw,setPw]=useState(''); const [apps,setApps]=useState([]); const [authMode,setAuthMode]=useState('login'); const [newPw,setNewPw]=useState(''); const [confirmPw,setConfirmPw]=useState(''); const [recoveryType,setRecoveryType]=useState('mobile'); const [recoveryValue,setRecoveryValue]=useState(''); const [otp,setOtp]=useState(''); const [sentOtp,setSentOtp]=useState(''); const [section,setSection]=useState('dashboard'); const [service,setService]=useState(null); const [search,setSearch]=useState(''); const [now,setNow]=useState(new Date()); const [idle,setIdle]=useState(0); const [form,setForm]=useState({customer:'',mobile:'',work:'',sub:'',fee:''}); const [msg,setMsg]=useState(''); const [userForm,setUserForm]=useState({username:'',name:'',role:'Admin',mobile:'',email:'',password:''});
 useEffect(()=>{setApps(seedApps()); setAllUsers(seedUsers()); const saved=localStorage.getItem('mi_user'); if(saved)setUser(JSON.parse(saved)); const t=setInterval(()=>setNow(new Date()),1000); return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!user)return; const events=['mousemove','keydown','click','scroll','touchstart']; const reset=()=>setIdle(0); events.forEach(e=>window.addEventListener(e,reset)); const t=setInterval(()=>setIdle(x=>x+1),1000); return()=>{clearInterval(t);events.forEach(e=>window.removeEventListener(e,reset))}},[user]);
 useEffect(()=>{if(user&&idle>=1200){logout();}},[idle,user]);
 const stats=useMemo(()=>({total:apps.length,received:apps.filter(a=>a.status==='Received').length,processed:apps.filter(a=>a.status==='Processed').length,pending:apps.filter(a=>a.status==='Pending').length,completed:apps.filter(a=>a.status==='Completed').length}),[apps]);
 function getStoredPassword(username){return localStorage.getItem('mi_pw_'+username)}
 function doLogin(e){e.preventDefault(); const found=allUsers.find(x=>x.username.toLowerCase()===login.toLowerCase()); if(!found){setMsg('Username not found.');return} const stored=getStoredPassword(found.username); if(stored ? pw!==stored : pw!=='1234'){setMsg(stored?'Incorrect password. Use Forgot Password if needed.':'First login uses temporary password 1234.');return} const old=localStorage.getItem('mi_last_'+found.username); const u={...found,lastLogin:old||'First login'}; localStorage.setItem('mi_last_'+found.username,now.toLocaleString());localStorage.setItem('mi_user',JSON.stringify(u));setUser(u);setMsg('');setLogin('');setPw('')}
 function setPassword(e){e.preventDefault(); if(!login||!newPw||newPw.length<6||newPw!==confirmPw){setMsg('Choose a username and a matching password of at least 6 characters.');return} const found=allUsers.find(x=>x.username.toLowerCase()===login.toLowerCase()); if(!found){setMsg('Username not found.');return} localStorage.setItem('mi_pw_'+found.username,newPw); setMsg('Password saved. You can now sign in with your new password.'); setAuthMode('login'); setPw(''); setNewPw(''); setConfirmPw('')}
 function sendOtp(){const found=allUsers.find(x=>x.username.toLowerCase()===login.toLowerCase()); if(!found){setMsg('Enter a valid username first.');return} if(!recoveryValue){setMsg('Enter your registered mobile number or email.');return} const code=String(Math.floor(100000+Math.random()*900000)); setSentOtp(code); setOtp(''); setMsg('OTP generated for this prototype. Real SMS/email delivery must be connected before production use.')}
 function resetPassword(e){e.preventDefault(); if(!sentOtp||otp!==sentOtp){setMsg('Invalid OTP.');return} if(!newPw||newPw.length<6||newPw!==confirmPw){setMsg('New password must be at least 6 characters and match confirmation.');return} const found=allUsers.find(x=>x.username.toLowerCase()===login.toLowerCase()); localStorage.setItem('mi_pw_'+found.username,newPw); setMsg('Password reset successfully. Please sign in.'); setAuthMode('login'); setSentOtp(''); setOtp(''); setNewPw(''); setConfirmPw('')}
 function saveUser(e){e.preventDefault(); if(user.role!=='Master')return; if(!userForm.username||!userForm.name)return setMsg('Username and name are required.'); const username=userForm.username.toUpperCase().trim(); const exists=allUsers.find(x=>x.username===username); const next=exists?allUsers.map(x=>x.username===username?{...x,username,name:userForm.name,role:userForm.role,mobile:userForm.mobile,email:userForm.email}:x):[...allUsers,{username,name:userForm.name,role:userForm.role,mobile:userForm.mobile,email:userForm.email}]; setAllUsers(next); localStorage.setItem('mi_users',JSON.stringify(next)); if(userForm.password) localStorage.setItem('mi_pw_'+username,userForm.password); setUserForm({username:'',name:'',role:'Admin',mobile:'',email:'',password:''}); setMsg(exists?'User updated.':'User added.')}
function removeUser(username){if(user.role!=='Master'||username==='MASTER')return; const next=allUsers.filter(x=>x.username!==username); setAllUsers(next); localStorage.setItem('mi_users',JSON.stringify(next)); localStorage.removeItem('mi_pw_'+username); setMsg('User removed.')}
function logout(){localStorage.removeItem('mi_user');setUser(null);setIdle(0)}
 function openService(s){setService(s);setSection('service')}
 function createApp(e){e.preventDefault(); if(!form.customer||!form.mobile||!form.work||!form.sub)return setMsg('Please fill all application fields.'); const a={id:Date.now(),customer:form.customer,mobile:form.mobile,work:form.work,sub:form.sub,fee:Number(form.fee||0),status:'Received',created:now.toLocaleString()}; const next=[a,...apps];setApps(next);localStorage.setItem('mi_apps',JSON.stringify(next));setForm({customer:'',mobile:'',work:'',sub:'',fee:''});setMsg('Application created successfully.');setSection('dashboard')}
 if(!user)return <div className="login"><div className="loginCard"><div className="brandMark">MI</div><h1>MIRACLE INFOTECH</h1><p>Internet Center Management Portal</p>{authMode==='login'&&<><form onSubmit={doLogin}><input placeholder="Username" value={login} onChange={e=>setLogin(e.target.value)}/><input placeholder="Password" type="password" value={pw} onChange={e=>setPw(e.target.value)}/><button>Sign In</button></form><div className="authLinks"><button type="button" onClick={()=>{setAuthMode('set');setMsg('')}}>Set / Change Password</button><button type="button" onClick={()=>{setAuthMode('forgot');setMsg('')}}>Forgot Password?</button></div><small>First login temporary password: 1234. Set your own password after signing in.</small></>}{authMode==='set'&&<form onSubmit={setPassword}><input placeholder="Username (Master/Admin/Employee)" value={login} onChange={e=>setLogin(e.target.value)}/><input placeholder="New Password (6+ characters)" type="password" value={newPw} onChange={e=>setNewPw(e.target.value)}/><input placeholder="Confirm New Password" type="password" value={confirmPw} onChange={e=>setConfirmPw(e.target.value)}/><button>Save My Password</button><button type="button" className="secondaryBtn" onClick={()=>setAuthMode('login')}>Back to Sign In</button></form>}{authMode==='forgot'&&<form onSubmit={resetPassword}><input placeholder="Username" value={login} onChange={e=>setLogin(e.target.value)}/><div className="otpRow"><select value={recoveryType} onChange={e=>setRecoveryType(e.target.value)}><option value="mobile">Mobile OTP</option><option value="email">Email OTP</option></select><input placeholder={recoveryType==='mobile'?'Registered mobile':'Registered email'} value={recoveryValue} onChange={e=>setRecoveryValue(e.target.value)}/></div><button type="button" onClick={sendOtp}>Send OTP</button>{sentOtp&&<div className="demoOtp">Prototype OTP: <b>{sentOtp}</b></div>}<input placeholder="Enter OTP" inputMode="numeric" maxLength="6" value={otp} onChange={e=>setOtp(e.target.value)}/><input placeholder="New Password" type="password" value={newPw} onChange={e=>setNewPw(e.target.value)}/><input placeholder="Confirm New Password" type="password" value={confirmPw} onChange={e=>setConfirmPw(e.target.value)}/><button>Reset Password</button><button type="button" className="secondaryBtn" onClick={()=>setAuthMode('login')}>Back to Sign In</button></form>}{msg&&<div className="error">{msg}</div>}</div></div>;
 const filtered=apps.filter(a=>(a.customer+a.mobile+a.work+a.sub).toLowerCase().includes(search.toLowerCase()));
 const selected=service; const subs=selected?.sub||[];
 return <div className="app"><header><div><div className="logo">MIRACLE <span>INFOTECH</span></div><div className="tag">INTERNET CENTER</div></div><div className="topRight"><div className="userChip"><div className="avatar">{user.name[0]}</div><div><b>{user.name}</b><small>{user.role} · Last login: {user.lastLogin}</small></div></div><div className="clock"><Clock3 size={17}/><span>{now.toLocaleDateString('en-IN')}<br/><b>{now.toLocaleTimeString('en-IN')}</b></span></div><button className="logout" onClick={logout}><LogOut size={17}/> Logout</button></div></header>
 <main><aside><button className={section==='dashboard'?'nav active':'nav'} onClick={()=>{setSection('dashboard');setService(null)}}><LayoutDashboard/>Dashboard</button><button className={section==='create'?'nav active':'nav'} onClick={()=>setSection('create')}><Plus/>Create Application</button><button className="nav" onClick={()=>setSection('applications')}><FileEdit/>Application Modification</button>{user.role==='Master'&&<button className={section==='users'?'nav active':'nav'} onClick={()=>setSection('users')}><Users/>User Management</button>}<div className="sideTitle">SERVICES</div>{services.map(s=><button className="nav" key={s.id} onClick={()=>openService(s)}><s.icon/>{s.name}<ChevronRight size={14} className="push"/></button>)}</aside>
 <section className="content"><div className="searchBar"><Search size={18}/><input placeholder="Search applications, customer, mobile, work..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {section==='dashboard'&&<><div className="welcome"><div><div className="eyebrow">WORKSPACE</div><h2>Welcome, {user.name}</h2><p>Manage your internet center applications from one place.</p></div><button onClick={()=>setSection('create')}><Plus size={18}/> New Application</button></div><div className="stats">{[['Total Applications',stats.total,Activity],['Received',stats.received,Inbox],['Processed',stats.processed,LoaderCircle],['Pending',stats.pending,Hourglass],['Completed',stats.completed,CheckCircle2]].map(([n,v,I])=><div className="stat" key={n}><div className="statIcon"><I/></div><div><span>{n}</span><strong>{v}</strong></div></div>)}</div><h3>Services</h3><div className="serviceGrid">{services.map(s=><button className="serviceCard" key={s.id} onClick={()=>openService(s)}><div className="serviceImageWrap"><img className="serviceImage" src={s.image} alt={s.name}/><div className="serviceImageIcon"><s.icon/></div></div><b>{s.name}</b><span>{s.sub.length} sub-services</span><ChevronRight/></button>)}</div><h3>Recent Applications</h3><AppsTable data={filtered.slice(0,8)} /></>}
 {section==='service'&&selected&&<><div className="pageHead"><div><div className="eyebrow">SERVICE</div><h2>{selected.name}</h2><p>Select a sub-work to enter its configured URL.</p></div><button className="back" onClick={()=>setSection('dashboard')}>Back to Dashboard</button></div><div className="subGrid">{subs.map((x,i)=><button className="subCard" key={x} onClick={()=>window.open(selected.urls[i],'_blank','noopener,noreferrer')}><div className="smallIcon"><selected.icon/></div><div><b>{x}</b><span>Open service URL</span></div><ExternalLink/></button>)}</div></>}
 {section==='create'&&<><div className="pageHead"><div><div className="eyebrow">APPLICATIONS</div><h2>Create Application</h2><p>Enter customer and service details.</p></div></div><form className="formCard" onSubmit={createApp}><label>Customer Name<input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Mobile Number<input inputMode="numeric" maxLength="10" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label>Work<select value={form.work} onChange={e=>{const s=services.find(x=>x.name===e.target.value);setForm({...form,work:e.target.value,sub:'',fee:s?.fee||''})}}><option value="">Select work</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Sub-work<select value={form.sub} onChange={e=>setForm({...form,sub:e.target.value})} disabled={!form.work}><option value="">Select sub-work</option>{services.find(s=>s.name===form.work)?.sub.map(x=><option key={x}>{x}</option>)}</select></label><label>Default / Service Fee<input type="number" min="0" value={form.fee} onChange={e=>setForm({...form,fee:e.target.value})}/></label><div className="formActions"><button type="submit"><Plus/>Create Application</button><button type="button" className="secondary" onClick={()=>setSection('dashboard')}>Cancel</button></div>{msg&&<div className="success">{msg}</div>}</form></>}
 {section==='users'&&user.role==='Master'&&<><div className="pageHead"><div><div className="eyebrow">MASTER CONTROL</div><h2>User Management</h2><p>Add, edit and manage Admin and Employee accounts.</p></div></div><form className="formCard" onSubmit={saveUser}><label>Username<input value={userForm.username} onChange={e=>setUserForm({...userForm,username:e.target.value})} placeholder="ADMIN / EMPLOYEE"/></label><label>Name<input value={userForm.name} onChange={e=>setUserForm({...userForm,name:e.target.value})}/></label><label>Role<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option>Admin</option><option>Employee</option></select></label><label>Mobile Number<input value={userForm.mobile} onChange={e=>setUserForm({...userForm,mobile:e.target.value})}/></label><label>Email<input type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Password (optional)<input type="password" value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})} placeholder="Leave blank to keep current"/></label><div className="formActions"><button type="submit"><Plus/>Save User</button></div>{msg&&<div className="success">{msg}</div>}</form><h3>Accounts</h3><div className="tableCard"><div className="tableHead"><span>Username / Name</span><span>Role</span><span>Mobile</span><span>Email</span><span>Action</span></div>{allUsers.map(u=><div className="row" key={u.username}><div><b>{u.username}</b><small>{u.name}</small></div><div>{u.role}</div><div>{u.mobile||'—'}</div><div>{u.email||'—'}</div><div>{u.username==='MASTER'?<span>Protected</span>:<button className="dangerBtn" onClick={()=>removeUser(u.username)}>Remove</button>}</div></div>)}</div></>}{section==='applications'&&<><div className="pageHead"><div><div className="eyebrow">APPLICATIONS</div><h2>Application Modification</h2><p>Search and update application status.</p></div></div><AppsTable data={filtered} editable setApps={setApps}/></>}
 </section></main><footer><span><ShieldCheck size={15}/> Secure workspace</span><span>Auto logout after 20 minutes of inactivity</span></footer></div>
}
function AppsTable({data,editable,setApps}){return <div className="tableCard"><div className="tableHead"><span>Customer</span><span>Work / Sub-work</span><span>Fee</span><span>Status</span><span>Created</span></div>{data.length?data.map(a=><div className="row" key={a.id}><div><b>{a.customer}</b><small>{a.mobile}</small></div><div><b>{a.work}</b><small>{a.sub}</small></div><div>₹{a.fee}</div><div>{editable?<select value={a.status} onChange={e=>{const next=data.map(x=>x.id===a.id?{...x,status:e.target.value}:x);setApps(prev=>{const all=prev.map(x=>x.id===a.id?{...x,status:e.target.value}:x);localStorage.setItem('mi_apps',JSON.stringify(all));return all})}}><option>Received</option><option>Processed</option><option>Pending</option><option>Completed</option></select>:<span className={'pill '+a.status.toLowerCase()}>{a.status}</span>}</div><small>{a.created}</small></div>):<div className="empty">No applications yet.</div>}</div>}
